# Generated by Django 3.0 on 2020-09-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='количество'),
        ),
    ]
