# Generated by Django 3.0 on 2020-09-04 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200830_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 12, 57, 27, 577836), verbose_name='Актуальность ключа'),
        ),
    ]
