# Generated by Django 3.0 on 2020-09-05 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200904_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 16, 15, 25, 666240), verbose_name='Актуальность ключа'),
        ),
    ]
